# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Astral < Formula
  desc "Calculations for the position of the sun and moon."
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sj14/astral/releases/download/v0.2.0/astral_0.2.0_darwin_amd64"
      sha256 "dfe4cff44bd775d38e26a70db1c6764ae865d4d47db451e94ee61c36fbbad70a"

      def install
        bin.install "astral_0.2.0_darwin_amd64" => "astral"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sj14/astral/releases/download/v0.2.0/astral_0.2.0_darwin_arm64"
      sha256 "8a5133488850d6aa9305b4beaa2afb054e875fb45b5c36118d0d4bc0ba428094"

      def install
        bin.install "astral_0.2.0_darwin_arm64" => "astral"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sj14/astral/releases/download/v0.2.0/astral_0.2.0_linux_amd64"
      sha256 "737f8415396557e20712679aadafee726a1757afda3b29ba90e7500798b9d836"

      def install
        bin.install "astral_0.2.0_linux_amd64" => "astral"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sj14/astral/releases/download/v0.2.0/astral_0.2.0_linux_arm64"
      sha256 "dd5d464b7d0e712770d28104b261bb4b48c9c29ff8a12a8d236ce7e8ad8f77e2"

      def install
        bin.install "astral_0.2.0_linux_arm64" => "astral"
      end
    end
  end
end
