# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Confible < Formula
  desc "Confible is a simple configuration tool for your local machine."
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sj14/confible/releases/download/v0.1.1/confible_0.1.1_darwin_amd64.tar.gz"
      sha256 "436ca4f34a15dc9b3a37c007033861081fda33769e15aa66af80715bb188843f"

      def install
        bin.install "confible"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sj14/confible/releases/download/v0.1.1/confible_0.1.1_darwin_arm64.tar.gz"
      sha256 "1a3d912ae9d0abc30062c56474c2df9cea5f0ed871aa6ccf4a0d2c963c6e2a77"

      def install
        bin.install "confible"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sj14/confible/releases/download/v0.1.1/confible_0.1.1_linux_armv6.tar.gz"
      sha256 "33f14cd4f2cd69ccfa157b934ea25cfacd1d58860ec1a8aaa84e62e6298ddcc2"

      def install
        bin.install "confible"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sj14/confible/releases/download/v0.1.1/confible_0.1.1_linux_arm64.tar.gz"
      sha256 "432fc480b80f514281106acbb324b072c30762ec9e35fa78b6bcb052bb6465a2"

      def install
        bin.install "confible"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sj14/confible/releases/download/v0.1.1/confible_0.1.1_linux_amd64.tar.gz"
      sha256 "87e0ca4273fb778f8611287be5e391afa570eb75cb03b7a958fbb5f8db9ab2dd"

      def install
        bin.install "confible"
      end
    end
  end
end
