# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Confible < Formula
  desc "Confible is a simple configuration tool for your local machine."
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sj14/confible/releases/download/v0.1.0/confible_0.1.0_darwin_arm64.tar.gz"
      sha256 "3b4e7bd8ef4a1e95f3838f37d53568db32e2b331e54a8459e5b94a930ba8223f"

      def install
        bin.install "confible"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sj14/confible/releases/download/v0.1.0/confible_0.1.0_darwin_amd64.tar.gz"
      sha256 "b29dd8fa01503bb2ea852610de377d05535a6afd5e2238581d676d0ad0eae546"

      def install
        bin.install "confible"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sj14/confible/releases/download/v0.1.0/confible_0.1.0_linux_arm64.tar.gz"
      sha256 "73c08b6f25a469fb6e54320a9e8159a9ea7900020c02a587788c9fccbaf60fd8"

      def install
        bin.install "confible"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sj14/confible/releases/download/v0.1.0/confible_0.1.0_linux_armv6.tar.gz"
      sha256 "9253de950f6b1d014eb53b6123ce1b3f1023c46e78fc9b040e7272ae83aeb5fc"

      def install
        bin.install "confible"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sj14/confible/releases/download/v0.1.0/confible_0.1.0_linux_amd64.tar.gz"
      sha256 "8bee89c688fca8a07636ae03a3df9272e61d358c82bfc3a8c4679380b5365b1c"

      def install
        bin.install "confible"
      end
    end
  end
end
