# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Epoch < Formula
  desc "Easily convert epoch timestamps to human readable formats and vice versa."
  homepage ""
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sj14/epoch/releases/download/v0.2.2/epoch_0.2.2_darwin_amd64"
      sha256 "fa786103e3db4774d58249700356ee6a34c8eaf2bf346c01d1f6b96f199d1492"

      def install
        bin.install "epoch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sj14/epoch/releases/download/v0.2.2/epoch_0.2.2_darwin_arm64"
      sha256 "c0de3bbfbe1849d774ff63d83405f168fc0b099f87206188994ea3b6ffc46386"

      def install
        bin.install "epoch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sj14/epoch/releases/download/v0.2.2/epoch_0.2.2_linux_amd64"
        sha256 "a1e0452e1c721e747670151e36c88d9728ac1e8ac344b2ac05e473856bc4607b"

        def install
          bin.install "epoch"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sj14/epoch/releases/download/v0.2.2/epoch_0.2.2_linux_arm64"
        sha256 "3af1dca90474270106cae8743fc3e3d9477827488c8ca668d0f5a602d1b15d4f"

        def install
          bin.install "epoch"
        end
      end
    end
  end
end
