# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jellyctl < Formula
  desc "A CLI for managing your Jellyfin server"
  homepage ""
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/sj14/jellyctl/releases/download/v0.3.0/jellyctl_0.3.0_darwin_amd64"
      sha256 "ee1aa06cea53c432f3a97a3159d1d0240bef4143f0110cb1efe65edd93c6ca56"

      def install
        bin.install "jellyctl_0.3.0_darwin_amd64" => "jellyctl"
      end
    end
    on_arm do
      url "https://github.com/sj14/jellyctl/releases/download/v0.3.0/jellyctl_0.3.0_darwin_arm64"
      sha256 "5a274470b5d4f08b26e3387edec7cc94c6284ffe570f61cb4b4901f0e8e8c258"

      def install
        bin.install "jellyctl_0.3.0_darwin_arm64" => "jellyctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sj14/jellyctl/releases/download/v0.3.0/jellyctl_0.3.0_linux_amd64"
        sha256 "578e7e2bc24b37318cabe4da5d6d022137dd9d5b67b9120b1707463b0d6962a6"

        def install
          bin.install "jellyctl_0.3.0_linux_amd64" => "jellyctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sj14/jellyctl/releases/download/v0.3.0/jellyctl_0.3.0_linux_arm64"
        sha256 "88aa86505ae59261091b5be60b700055c059170b7e591a91c4d46c916fde4941"

        def install
          bin.install "jellyctl_0.3.0_linux_arm64" => "jellyctl"
        end
      end
    end
  end
end
