# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jellyctl < Formula
  desc "A CLI for managing your Jellyfin server"
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sj14/jellyctl/releases/download/v0.1.0/jellyctl_0.1.0_darwin_amd64"
      sha256 "7a70e8e7e4db88d3ebe59408fd8f6aaeaa8c05a5474c99b9fd5a1b10191f932b"

      def install
        bin.install "jellyctl_0.1.0_darwin_amd64" => "jellyctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sj14/jellyctl/releases/download/v0.1.0/jellyctl_0.1.0_darwin_arm64"
      sha256 "409f2728bb5821cef2de977a37a6b450489d1a4faff53ad772f384a36811b410"

      def install
        bin.install "jellyctl_0.1.0_darwin_arm64" => "jellyctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sj14/jellyctl/releases/download/v0.1.0/jellyctl_0.1.0_linux_amd64"
      sha256 "633b39e2f69e79e9b5ffe264dbc2dac4ea528d89fe72bfa68cee8694d6737020"

      def install
        bin.install "jellyctl_0.1.0_linux_amd64" => "jellyctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sj14/jellyctl/releases/download/v0.1.0/jellyctl_0.1.0_linux_arm64"
      sha256 "736927adfc487f7d59626420149d556ab864d8059c5b5840104b63d859f41582"

      def install
        bin.install "jellyctl_0.1.0_linux_arm64" => "jellyctl"
      end
    end
  end
end
