# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubedump < Formula
  desc "Tool for dumping manifests from your Kubernetes clusters"
  homepage ""
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sj14/kubedump/releases/download/v0.3.0/kubedump_0.3.0_darwin_amd64"
      sha256 "ccdd2d51a16331ab79a9761951305597b87d01d0769508ebdcec34eac6193413"

      def install
        bin.install "kubedump_0.3.0_darwin_amd64" => "kubedump"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sj14/kubedump/releases/download/v0.3.0/kubedump_0.3.0_darwin_arm64"
      sha256 "655cccb6951e818e2090dedb2038bac98d0134fd680535e6afe38ca3820501a7"

      def install
        bin.install "kubedump_0.3.0_darwin_arm64" => "kubedump"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sj14/kubedump/releases/download/v0.3.0/kubedump_0.3.0_linux_amd64"
      sha256 "50d801f19c6dac79a71b1c698cd1be27e6984f11e45623d25d152dd73bf33ad1"

      def install
        bin.install "kubedump_0.3.0_linux_amd64" => "kubedump"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sj14/kubedump/releases/download/v0.3.0/kubedump_0.3.0_linux_arm64"
      sha256 "f8adffff1a23ca0aba2647b83282cfc6b11312a9a3eecee54fb4b307fdbb4105"

      def install
        bin.install "kubedump_0.3.0_linux_arm64" => "kubedump"
      end
    end
  end
end
