# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Multicode < Formula
  desc "Decode bits, hex, base64 and protobuf recursively with a single command"
  homepage ""
  version "0.2.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sj14/multicode/releases/download/v0.2.3/decode_0.2.3_darwin_amd64"
      sha256 "3a9792b035a4c905ffb48b7e21ec2d11813638aa360340f3c1e6d83d2fbadcda"

      define_method(:install) do
        bin.install "decode_0.2.3_darwin_amd64" => "decode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sj14/multicode/releases/download/v0.2.3/decode_0.2.3_darwin_arm64"
      sha256 "ea15524a83914b32315e1f6ea04df3f438e9c4be3ebda543c2f38829319627ac"

      define_method(:install) do
        bin.install "decode_0.2.3_darwin_arm64" => "decode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sj14/multicode/releases/download/v0.2.3/decode_0.2.3_linux_amd64"
      sha256 "ac29359afb559426204cbdcd604a9022ba6abbbfdec323a530fbc08ef47703f5"
      define_method(:install) do
        bin.install "decode_0.2.3_linux_amd64" => "decode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sj14/multicode/releases/download/v0.2.3/decode_0.2.3_linux_arm64"
      sha256 "ddb876b0925c0aec691e6bae08c4b699b180c4f9879c6e1dc2edd8cc75a97993"
      define_method(:install) do
        bin.install "decode_0.2.3_linux_arm64" => "decode"
      end
    end
  end
end
