# This file was generated by GoReleaser. DO NOT EDIT.
class Multicode < Formula
  desc "Decode hex, base64 and protobuf recursively with a single command"
  homepage ""
  version "0.1.1"

  if OS.mac?
    url "https://github.com/sj14/multicode/releases/download/v0.1.1/multicode_0.1.1_darwin_amd64.tar.gz"
    sha256 "051ca07e8f9629864a540cd891960309b89c05a0d1d18721fa4f61e3d22bafd3"
  elsif OS.linux?
    url "https://github.com/sj14/multicode/releases/download/v0.1.1/multicode_0.1.1_linux_amd64.tar.gz"
    sha256 "7345ab4c3c607f0ebf9d02cb8c3edd32271366adf1dcbde42fac731deb641c98"
  end

  def install
    bin.install "multicode"
  end
end
