# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sss < Formula
  desc "S3 clietn"
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sj14/sss/releases/download/v0.1.0/sss_0.1.0_darwin_amd64"
      sha256 "af9329285e92ef7e02bea6ab76a21d81780423dd174923b3ec1bf831aa9f1a44"

      def install
        bin.install "sss_0.1.0_darwin_amd64" => "sss"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sj14/sss/releases/download/v0.1.0/sss_0.1.0_darwin_arm64"
      sha256 "7636262c19267d3d723ffa9a645211d81f9014bf6514debed42f732953adeb4f"

      def install
        bin.install "sss_0.1.0_darwin_arm64" => "sss"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sj14/sss/releases/download/v0.1.0/sss_0.1.0_linux_amd64"
      sha256 "525c32806ff759cf99b5b5e8a3d6cd5670ed2b9f06e5e142e90e8835ca476d8f"
      def install
        bin.install "sss_0.1.0_linux_amd64" => "sss"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sj14/sss/releases/download/v0.1.0/sss_0.1.0_linux_arm64"
      sha256 "d92dfcbf9570b29d6ed0ee591c43144eea39d10a0ed9b50a7095292a982c1a7f"
      def install
        bin.install "sss_0.1.0_linux_arm64" => "sss"
      end
    end
  end
end
