# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Urlenc < Formula
  desc "Convert an URL-encoded or URL-decoded input string."
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sj14/urlenc/releases/download/v0.0.1/urlenc_0.0.1_darwin_amd64.tar.gz"
      sha256 "797388be2bff85435865af71652cc3a8102bd1b7f8178e766c395fa0c8875c15"

      def install
        bin.install "urlenc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sj14/urlenc/releases/download/v0.0.1/urlenc_0.0.1_darwin_arm64.tar.gz"
      sha256 "e34ce55c70ef16a0f9bcf9b8e03c04e50d3e0d1025c81ad5d23862747b6d7780"

      def install
        bin.install "urlenc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sj14/urlenc/releases/download/v0.0.1/urlenc_0.0.1_linux_arm64.tar.gz"
      sha256 "0913be9401a6e548afa6494a6b691e0c4380c7fee8f4f103d11806363e6673bf"

      def install
        bin.install "urlenc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sj14/urlenc/releases/download/v0.0.1/urlenc_0.0.1_linux_amd64.tar.gz"
      sha256 "680546dcc1b64e0c83b983df4126ae9b44c374f147900d7767f93a5f2dcf9c6f"

      def install
        bin.install "urlenc"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sj14/urlenc/releases/download/v0.0.1/urlenc_0.0.1_linux_armv6.tar.gz"
      sha256 "de1e692a1a779b588c1ca541126b18b62b5e6c061844853f2fdac3fc23a29a86"

      def install
        bin.install "urlenc"
      end
    end
  end
end
