# This file was generated by GoReleaser. DO NOT EDIT.
cask "epoch" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "e8ebe2f3e064f2809d8275a0279408e87dc66515d44fc73212e7b229ae371304"
      url "https://github.com/sj14/epoch/releases/download/v#{version}/epoch_#{version}_darwin_amd64"
      binary "epoch_0.2.3_darwin_amd64", target: "epoch"
    end
    on_arm do
      sha256 "544c520470e62635c354ea9ae3f40599516b4050ddb465da80a962b948dcbdee"
      url "https://github.com/sj14/epoch/releases/download/v#{version}/epoch_#{version}_darwin_arm64"
      binary "epoch_0.2.3_darwin_arm64", target: "epoch"
    end
  end

  on_linux do
    on_intel do
      sha256 "18c5e1aad3a0c009cea714daef3a64d634d7ebb7549e7a1b61f0cdba63f4020e"
      url "https://github.com/sj14/epoch/releases/download/v#{version}/epoch_#{version}_linux_amd64"
      binary "epoch_0.2.3_linux_amd64", target: "epoch"
    end
    on_arm do
      sha256 "c25b3e88fef7c31b7b8a94a41d0ac54a50247deecc5b49787c6f3015c6126083"
      url "https://github.com/sj14/epoch/releases/download/v#{version}/epoch_#{version}_linux_arm64"
      binary "epoch_0.2.3_linux_arm64", target: "epoch"
    end
  end

  name "epoch"
  desc "Easily convert epoch timestamps to human readable formats and vice versa."
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
