# This file was generated by GoReleaser. DO NOT EDIT.
cask "sss" do
  name "sss"
  desc "S3 client"
  homepage ""
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_intel do
      url "https://github.com/sj14/sss/releases/download/v#{version}/sss_#{version}_darwin_amd64"
      sha256 "dfd68ba5b95debbde11db4297c06ce515d78993e3b859c0b61691e012e3f33e6"
      binary "sss_0.2.0_darwin_amd64", target: "sss"
    end
    on_arm do
      url "https://github.com/sj14/sss/releases/download/v#{version}/sss_#{version}_darwin_arm64"
      sha256 "41cc7804d952ed6a8b69ce385b58507218ae55bbcbab648e5a22d77ef460e4dc"
      binary "sss_0.2.0_darwin_arm64", target: "sss"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sj14/sss/releases/download/v#{version}/sss_#{version}_linux_amd64"
      sha256 "816f0b1b41a2e1031219e035c14619ad7922f860eee877f893ea691fef06854a"
      binary "sss_0.2.0_linux_amd64", target: "sss"
    end
    on_arm do
      url "https://github.com/sj14/sss/releases/download/v#{version}/sss_#{version}_linux_arm64"
      sha256 "49dfe038d7b6485a6b8e6ae868d7a2921dbdca3fa0bc621d3c9620595901a10d"
      binary "sss_0.2.0_linux_arm64", target: "sss"
    end
  end

  # No zap stanza required
end
